spring.application.name=worker
spring.main.web-application-type=none
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/platform}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:platform}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:platform}
spring.flyway.enabled=false
platform.events.queue.endpoint=http://127.0.0.1:4566
platform.events.queue.region=us-east-1
platform.events.queue.name=accepted-events
platform.events.queue.poll-enabled=true
