spring.application.name=platform-service
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.flyway.enabled=true
spring.session.jdbc.initialize-schema=never
spring.session.timeout=30m
platform.events.queue.endpoint=http://127.0.0.1:4566
platform.events.queue.region=us-east-1
platform.events.queue.name=accepted-events
